services:
    bitbag_sylius_przelewy24_plugin.action.capture:
        class: BitBag\SyliusPrzelewy24Plugin\Action\CaptureAction
        public: true
        arguments:
            - "@bitbag_sylius_przelewy24_plugin.bridge.przelewy24"
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: payum.action, factory: przelewy24, alias: payum.action.capture }

    bitbag_sylius_przelewy24_plugin.action.notify:
        class: BitBag\SyliusPrzelewy24Plugin\Action\NotifyAction
        public: true
        arguments:
            - "@bitbag_sylius_przelewy24_plugin.bridge.przelewy24"
        tags:
            - { name: payum.action, factory: przelewy24, alias: payum.action.notify }

    bitbag_sylius_przelewy24_plugin.action.status:
        class: BitBag\SyliusPrzelewy24Plugin\Action\StatusAction
        public: true
        arguments:
            - "@bitbag_sylius_przelewy24_plugin.bridge.przelewy24"
        tags:
            - { name: payum.action, factory: przelewy24, alias: payum.action.status }

    bitbag_sylius_przelewy24_plugin.action.convert_payment:
        class: BitBag\SyliusPrzelewy24Plugin\Action\ConvertPaymentAction
        public: true
        arguments:
            - "@sylius.payment_description_provider"
        tags:
            - { name: payum.action, factory: przelewy24, alias: payum.action.convert_payment }
